name: CI/CD Pipeline with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: docker build -t vancetechwell/flask-app:latest .

    # Step 4: Run tests inside the container
    - name: Test Docker image
      run: |
        docker run --rm vancetechwell/flask-app:latest curl -s http://localhost:5000 | grep "Hello, Docker CI/CD!"

    # Step 5: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: docker push vancetechwell/flask-app:latest
